#!/usr/bin/env bash
# Configures /etc/hosts so localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8

new_hosts=$(sed 's/^127\.0\.0\.1\([[:space:]]\+\)localhost/127.0.0.2\1localhost/' /etc/hosts)
printf '%s\n8.8.8.8 facebook.com\n' "$new_hosts" > /etc/hosts
